### PR TITLE
Explore schema

### PR DESCRIPTION
**Pull request by oskjoh**
Added a cubelevels function to explore levels, did some refactoring of the code and made cube resitiction in cubemeasures, cubedimensions and cubelevels optional.

### CODE REVIEW

**Comment by piersharding** [comment]
Thanks for this - I am unable to test it but am happy to accept the PR if you are finished with it?

**Comment by oskjoh** [comment]
It works fine when interacting with the database I use at least. I realized however that I should add some documentation for the new functions. I’ll get back to you with an additional commit containing documentation.

**Comment by oskjoh** [comment]
I modified my PR branch so that it does not contain the commits of the other PR:s. Moreover, I've added documentation for the cubelevels, cubemeasures, cubedimensions and cubeexplore functions and modified the version number from 1.1 to 1.2.

Just tell me if you want me to modify anything before you accept the PR.

**Comment by piersharding** [comment]
Thanks for this - merged.

**Pull request merged**
